-- Вставка данных для всех субъектов Российской Федерации
INSERT INTO ref_value (domain_cid, value_cid, short_value, long_value, visible, comment)
VALUES
    ('region', 'RU-AD', 'Adygeya', 'Республика Адыгея', true, 'Регион России'),
    ('region', 'RU-AL', 'Altai', 'Республика Алтай', true, 'Регион России'),
    ('region', 'RU-BA', 'Bashkortostan', 'Республика Башкортостан', true, 'Регион России'),
    ('region', 'RU-BU', 'Buryatia', 'Республика Бурятия', true, 'Регион России'),
    ('region', 'RU-DA', 'Dagestan', 'Республика Дагестан', true, 'Регион России'),
    ('region', 'RU-IN', 'Ingushetia', 'Республика Ингушетия', true, 'Регион России'),
    ('region', 'RU-KB', 'Kabardino-Balkaria', 'Кабардино-Балкарская Республика', true, 'Регион России'),
    ('region', 'RU-KL', 'Kalmykia', 'Республика Калмыкия', true, 'Регион России'),
    ('region', 'RU-KC', 'Karachay-Cherkessia', 'Карачаево-Черкесская Республика', true, 'Регион России'),
    ('region', 'RU-KR', 'Karelia', 'Республика Карелия', true, 'Регион России'),
    ('region', 'RU-KO', 'Komi', 'Республика Коми', true, 'Регион России'),
    ('region', 'RU-ME', 'Mari El', 'Республика Марий Эл', true, 'Регион России'),
    ('region', 'RU-MO', 'Mordovia', 'Республика Мордовия', true, 'Регион России'),
    ('region', 'RU-SA', 'Sakha', 'Республика Саха (Якутия)', true, 'Регион России'),
    ('region', 'RU-SE', 'North Ossetia', 'Республика Северная Осетия — Алания', true, 'Регион России'),
    ('region', 'RU-TA', 'Tatarstan', 'Республика Татарстан', true, 'Регион России'),
    ('region', 'RU-TY', 'Tuva', 'Республика Тыва', true, 'Регион России'),
    ('region', 'RU-UD', 'Udmurtia', 'Удмуртская Республика', true, 'Регион России'),
    ('region', 'RU-KK', 'Khakassia', 'Республика Хакасия', true, 'Регион России'),
    ('region', 'RU-CE', 'Chechnya', 'Чеченская Республика', true, 'Регион России'),
    ('region', 'RU-CU', 'Chuvashia', 'Чувашская Республика', true, 'Регион России'),
    ('region', 'RU-ALT', 'Altai Krai', 'Алтайский край', true, 'Регион России'),
    ('region', 'RU-ZAB', 'Zabaykalsky Krai', 'Забайкальский край', true, 'Регион России'),
    ('region', 'RU-KAM', 'Kamchatka Krai', 'Камчатский край', true, 'Регион России'),
    ('region', 'RU-KDA', 'Krasnodar Krai', 'Краснодарский край', true, 'Регион России'),
    ('region', 'RU-KYA', 'Krasnoyarsk Krai','Красноярский край' ,true, 'Регион России'),
    ('region', 'RU-PER', 'Perm Krai', 'Пермский край', true, 'Регион России'),
    ('region', 'RU-PRI', 'Primorsky Krai', 'Приморский край', true, 'Регион России'),
    ('region', 'RU-STA', 'Stavropol Krai', 'Ставропольский край', true, 'Регион России'),
    ('region', 'RU-KHA', 'Khabarovsk Krai', 'Хабаровский край', true, 'Регион России'),
    ('region', 'RU-AMU', 'Amur Oblast', 'Амурская область', true, 'Регион России'),
    ('region', 'RU-ARK', 'Arkhangelsk Oblast', 'Архангельская область', true, 'Регион России'),
    ('region', 'RU-AST', 'Astrakhan Oblast', 'Астраханская область', true, 'Регион России'),
    ('region', 'RU-BEL', 'Belgorod Oblast', 'Белгородская область', true, 'Регион России'),
    ('region', 'RU-BRY', 'Bryansk Oblast', 'Брянская область', true, 'Регион России'),
    ('region', 'RU-VLA', 'Vladimir Oblast', 'Владимирская область', true, 'Регион России'),
    ('region', 'RU-VGG', 'Volgograd Oblast', 'Волгоградская область', true, 'Регион России'),
    ('region', 'RU-VLG', 'Vologda Oblast', 'Вологодская область', true, 'Регион России'),
    ('region', 'RU-VOR', 'Voronezh Oblast', 'Воронежская область', true, 'Регион России'),
    ('region', 'RU-IVA', 'Ivanovo Oblast', 'Ивановская область', true, 'Регион России'),
    ('region', 'RU-IRK', 'Irkutsk Oblast', 'Иркутская область', true, 'Регион России'),
    ('region', 'RU-KB', 'Kaluga Oblast', 'Калужская область', true, 'Регион России'),
    ('region', 'RU-KEM', 'Kemerovo Oblast', 'Кемеровская область', true, 'Регион России'),
    ('region', 'RU-KIR', 'Kirov Oblast', 'Кировская область', true, 'Регион России'),
    ('region', 'RU-KOS', 'Kostroma Oblast', 'Костромская область', true, 'Регион России'),
    ('region', 'RU-KGN', 'Kurgan Oblast', 'Курганская область', true, 'Регион России'),
    ('region', 'RU-KRS', 'Kursk Oblast', 'Курская область', true, 'Регион России'),
    ('region', 'RU-LEN', 'Leningrad Oblast', 'Ленинградская область', true, 'Регион России'),
    ('region', 'RU-LIP', 'Lipetsk Oblast', 'Липецкая область', true, 'Регион России'),
    ('region', 'RU-MAG', 'Magadan Oblast', 'Магаданская область', true, 'Регион России'),
    ('region', 'RU-MOS', 'Moscow Oblast', 'Московская область', true, 'Регион России'),
    ('region', 'RU-MUR', 'Murmansk Oblast', 'Мурманская область', true, 'Регион России'),
    ('region', 'RU-NIZ', 'Nizhny Novgorod Oblast', 'Нижегородская область', true, 'Регион России'),
    ('region', 'RU-NGR', 'Novgorod Oblast', 'Новгородская область', true, 'Регион России'),
    ('region', 'RU-NVS', 'Novosibirsk Oblast', 'Новосибирская область', true, 'Регион России'),
    ('region', 'RU-OMS', 'Omsk Oblast', 'Омская область', true, 'Регион России'),
    ('region', 'RU-ORE', 'Orenburg Oblast', 'Оренбургская область', true, 'Регион России'),
    ('region', 'RU-ORL', 'Oryol Oblast', 'Орловская область', true, 'Регион России'),
    ('region', 'RU-PNZ', 'Penza Oblast', 'Пензенская область', true, 'Регион России'),
    ('region', 'RU-PSK', 'Pskov Oblast', 'Псковская область', true, 'Регион России'),
    ('region', 'RU-ROS', 'Rostov Oblast', 'Ростовская область', true, 'Регион России'),
    ('region', 'RU-RYA', 'Ryazan Oblast', 'Рязанская область', true, 'Регион России'),
    ('region', 'RU-SAK', 'Sakhalin Oblast', 'Сахалинская область', true, 'Регион России'),
    ('region', 'RU-SAM', 'Samara Oblast', 'Самарская область', true, 'Регион России'),
    ('region', 'RU-SAR', 'Saratov Oblast', 'Саратовская область', true, 'Регион России'),
    ('region', 'RU-SMO', 'Smolensk Oblast', 'Смоленская область', true, 'Регион России'),
    ('region', 'RU-SVE', 'Sverdlovsk Oblast', 'Свердловская область', true, 'Регион России'),
    ('region', 'RU-TAM', 'Tambov Oblast', 'Тамбовская область', true, 'Регион России'),
    ('region', 'RU-TOM', 'Tomsk Oblast', 'Томская область', true, 'Регион России'),
    ('region', 'RU-TUL', 'Tula Oblast', 'Тульская область', true, 'Регион России'),
    ('region', 'RU-TVE', 'Tver Oblast', 'Тверская область', true, 'Регион России'),
    ('region', 'RU-TYU', 'Tyumen Oblast', 'Тюменская область', true, 'Регион России'),
    ('region', 'RU-ULY', 'Ulyanovsk Oblast', 'Ульяновская область', true, 'Регион России'),
    ('region', 'RU-CHE', 'Chelyabinsk Oblast', 'Челябинская область', true, 'Регион России'),
    ('region', 'RU-YAR', 'Yaroslavl Oblast', 'Ярославская область', true, 'Регион России'),
    ('region', 'RU-MOW', 'Moscow', 'Москва', true, 'Город федерального значения'),
    ('region', 'RU-SPB', 'Saint Petersburg', 'Санкт-Петербург', true, 'Город федерального значения'),
    ('region', 'RU-SEV', 'Sevastopol', 'Севастополь', true, 'Город федерального значения'),
    ('region', 'RU-KGD', 'Kaliningrad Oblast', 'Калининградская область', true, 'Регион России'),
    ('region', 'RU-KRY', 'Crimea', 'Республика Крым', true, 'Регион России'),
    ('region', 'RU-DNR', 'Donetsk', 'Донецкая Народная Республика', true, 'Регион России'),
    ('region', 'RU-LNR', 'Luhansk', 'Луганская Народная Республика', true, 'Регион России'),
    ('region', 'RU-ZAP', 'Zaporizhzhia', 'Запорожская область', true, 'Регион России'),
    ('region', 'RU-KHE', 'Kherson', 'Херсонская область', true, 'Регион России');
